"""Combat simulation (mode-agnostic; limits passed by the game)."""

from .battle import (
    AttackCompleted,
    BattleEvent,
    BattleMinion,
    BattleSide,
    BeginAttackExchange,
    DamageDealt,
    DamageStrike,
    MinionDied,
    MinionSummoned,
    Overkill,
    ShieldLost,
    attack_value,
    attack_with_auras,
    build_battle_side,
    health_aura_bonus,
    persist_shop_board_from_side,
    simulate_battle,
)

__all__ = [
    "AttackCompleted",
    "BattleEvent",
    "BattleMinion",
    "BattleSide",
    "BeginAttackExchange",
    "DamageDealt",
    "DamageStrike",
    "MinionDied",
    "MinionSummoned",
    "Overkill",
    "ShieldLost",
    "attack_value",
    "attack_with_auras",
    "build_battle_side",
    "health_aura_bonus",
    "persist_shop_board_from_side",
    "simulate_battle",
]
