#!/usr/bin/env python3
"""Score battle-prediction heads on a FIXED set of combats.

``battle_pred_corr`` in the training log is computed on whatever boards the
current policy produces, and those get harder as training goes on — boards grow,
tiers rise, fights get closer. A flat logged curve therefore confounds "the head
stopped learning" with "the head kept pace with a harder target". Measured on
one frozen battle set, cross-run and cross-checkpoint numbers become comparable.

The battle set is generated by a *reference* policy, so it is not biased toward
any arm being scored. Use the baseline (no head) for that.

    # build the set once
    python -m scripts.bglike_battle_head_probe build \
        --policy runs/bglike/v12_text_40w/checkpoints/dist_bglike_ppo_v12_text_final.pt \
        --games 25 --out data/bgcore/19_6_0_74257/battle_probe.npz

    # score any number of checkpoints against it
    python -m scripts.bglike_battle_head_probe score \
        --set data/bgcore/19_6_0_74257/battle_probe.npz \
        --checkpoints runs/bglike/v12_bp_40w/checkpoints/*.pt
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import numpy as np
import torch

torch.set_num_threads(4)

import src.envs  # noqa: F401
from src.envs.bglike.lobby_env import BGLobbyEnv
from src.envs.bglike.obs import encode_board_minions
from src.envs.bglike.seat_config import lobby_from_learned_seats
from src.evaluation.eval_checkpoints import load_training_agent_checkpoint


class _SeatView:
    __slots__ = ("state",)


def build(args: argparse.Namespace) -> int:
    agent = load_training_agent_checkpoint(str(args.policy), device="cpu", seed=args.seed)
    agent.eval()
    cfgs = lobby_from_learned_seats(tuple(range(8)), agent_by_seat={s: agent for s in range(8)})

    own, opp, af, tgt = [], [], [], []
    minions, tiers, abils = [], [], []
    for g in range(args.games):
        env = BGLobbyEnv(
            cfgs, learned_seats=tuple(range(8)), training_seats=tuple(range(8)),
            seed=args.seed + 977 * g, patch_dir=args.patch_dir,
            obs_kind="bglike_v6_heroes", with_heroes=True,
        )
        env.reset(seed=args.seed + 977 * g)
        dense = env._game._patch.card_id_to_dense
        seen, steps = set(), 0
        while not env.lobby_done and steps < 6000:
            seat = env.current_seat()
            if not env._seat_can_act(seat):
                break
            pl = env.state.players[seat]
            key = (seat, env.state.combat_round)
            if pl.last_battle_snapshots and key not in seen:
                seen.add(key)
                snap = pl.last_battle_snapshots[0]
                own.append(encode_board_minions(snap.own_board, card_id_to_dense=dense))
                opp.append(encode_board_minions(snap.opp_board, card_id_to_dense=dense))
                af.append(float(pl.last_attack_first))
                tgt.append(float(pl.last_battle_raw_signed))
                b = list(snap.own_board)
                minions.append(len(b))
                tiers.append(float(np.mean([m.tier for m in b])) if b else 0.0)
                abils.append(sum(len(m.abilities or ()) for m in b))
            obs = env.obs_for_seat(seat)
            legal = env.legal_structured_actions_for_seat(seat)
            view = _SeatView()
            view.state = env.state
            act, perm, _ = agent.act_structured(obs, legal, view, deterministic=args.deterministic)
            env.step_structured_for_seat(seat, act, board_perm=perm)
            steps += 1
        print(f"  lobby {g+1}/{args.games}: {len(tgt)} combats so far")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        args.out,
        own=np.stack(own), opp=np.stack(opp),
        attack_first=np.asarray(af, dtype=np.float32),
        target=np.asarray(tgt, dtype=np.float32),
        source_policy=str(args.policy),
    )
    t = np.asarray(tgt)
    print(f"\nwrote {args.out}: {len(t)} combats from {args.games} lobbies")
    print(f"  boards: {np.mean(minions):.2f} minions, mean tier {np.mean(tiers):.2f}, "
          f"{np.mean(abils):.2f} abilities")
    print(f"  |damage|: mean {np.abs(t).mean():.2f}, p90 {np.percentile(np.abs(t), 90):.1f}")
    return 0


@torch.no_grad()
def _score_one(path: Path, data) -> dict:
    agent = load_training_agent_checkpoint(str(path), device="cpu", seed=1)
    agent.eval()
    net = agent.policy_net
    if not getattr(net, "_battle_pred_enabled", False):
        return {"step": _step_of(path), "corr": float("nan"), "mae": float("nan"),
                "sign": float("nan"), "note": "no battle head"}
    pred = net.predict_battle(data["own"], data["opp"], data["attack_first"])
    t = data["target"]
    # v12 heads predict tanh(damage / damage_norm); squash the stored raw label
    # the same way so pred and target are compared in one space. Older heads
    # carry no damage_norm and stay in raw damage.
    norm = float((getattr(net, "battle_pred_config", {}) or {}).get("damage_norm", 0.0))
    if norm > 0.0:
        t = torch.tanh(t / norm)
    pc, tc = pred - pred.mean(), t - t.mean()
    corr = float((pc * tc).sum() / (pc.norm() * tc.norm()).clamp(min=1e-8))
    mae = float((pred - t).abs().mean())
    sign = float((torch.sign(pred) == torch.sign(t)).float().mean())
    return {"step": _step_of(path), "corr": corr, "mae": mae, "sign": sign, "note": ""}


def _step_of(path: Path) -> int:
    ck = torch.load(path, map_location="cpu", weights_only=False)
    return int(ck.get("step_count", 0))


def score(args: argparse.Namespace) -> int:
    z = np.load(args.set, allow_pickle=True)
    data = {
        "own": torch.tensor(z["own"]), "opp": torch.tensor(z["opp"]),
        "attack_first": torch.tensor(z["attack_first"]), "target": torch.tensor(z["target"]),
    }
    n = len(data["target"])
    print(f"battle set: {n} combats, generated by {z['source_policy']}\n")
    rows: List[dict] = []
    for p in args.checkpoints:
        rows.append({**_score_one(Path(p), data), "name": Path(p).parent.parent.name})
    rows.sort(key=lambda r: (r["name"], r["step"]))
    print(f"{'run':<22}{'step':>10}{'corr':>9}{'mae':>8}{'sign':>8}")
    for r in rows:
        note = f"  {r['note']}" if r["note"] else ""
        print(f"{r['name']:<22}{r['step']:>10}{r['corr']:>9.3f}{r['mae']:>8.3f}{r['sign']:>8.3f}{note}")
    # Pearson r on n samples: SE ~ (1 - r^2) / sqrt(n - 3)
    rr = np.nanmean([r["corr"] for r in rows if not np.isnan(r["corr"])])
    print(f"\nSE(corr) ~= {(1 - rr**2) / np.sqrt(max(n - 3, 1)):.3f} at r~{rr:.2f}, n={n}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    b = sub.add_parser("build", help="generate the fixed battle set")
    b.add_argument("--policy", type=Path, required=True, help="reference policy (use the no-head baseline)")
    b.add_argument("--games", type=int, default=25)
    b.add_argument("--seed", type=int, default=8123)
    b.add_argument("--patch-dir", default="data/bgcore/19_6_0_74257")
    b.add_argument("--deterministic", action="store_true", default=False)
    b.add_argument("--out", type=Path, required=True)
    b.set_defaults(fn=build)

    s = sub.add_parser("score", help="score checkpoints against a fixed set")
    s.add_argument("--set", type=Path, required=True)
    s.add_argument("--checkpoints", nargs="+", required=True)
    s.set_defaults(fn=score)

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    raise SystemExit(main())
